### ISSUE TITLE
ojdbc6.jar is MPL by Harvard DBMI?

### ISSUE THREAD

**Issue by dckc** [hms-dbmi/docker-images#7]
This docker stuff for i2b2 and transmart looks really promising. In evaluating whether it's suitable for us to use (KU Med Center), I see...

https://github.com/hms-dbmi/docker-images/blob/master/irct/LICENSE says MPL

The commit message for https://github.com/hms-dbmi/docker-images/blob/master/irct/oracle/ojdbc6.jar doesn't say anything special about who wrote it; it was committed by @recursethis in b4ada77 on Apr 4. Is that really when and by whom it was written?

cc @avillach

**Comment by avillach** [comment]
Yes
https://github.com/recursethis is Andre Rosa, the Docker guy in our team

Paul


On Jun 23, 2017, at 10:33 AM, Dan Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


This docker stuff for i2b2 and transmart looks really promising. In evaluating whether it's suitable for us to use (KU Med Center), I see...

https://github.com/hms-dbmi/docker-images/blob/master/irct/LICENSE<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hms-2Ddbmi_docker-2Dimages_blob_master_irct_LICENSE&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=lHl6mcA1LFiirClmNasU32yWmIRXU2N8uYMaP0t2ykI&m=7T3yuDhhEfjIbO4hLj0hFJaOPVj6TEk-tYKgP_T0zZE&s=_eoxLn2cy_gS7UZ0sMk-cBRKrdsE5LClXG4ngAVl6sc&e=> says MPL

The commit message for https://github.com/hms-dbmi/docker-images/blob/master/irct/oracle/ojdbc6.jar<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hms-2Ddbmi_docker-2Dimages_blob_master_irct_oracle_ojdbc6.jar&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=lHl6mcA1LFiirClmNasU32yWmIRXU2N8uYMaP0t2ykI&m=7T3yuDhhEfjIbO4hLj0hFJaOPVj6TEk-tYKgP_T0zZE&s=iWx5tmCoygPc92w5NoH3PFVsjxzvOFj_iEiI9j2ZGCo&e=> doesn't say anything special about who wrote it; it was committed by @recursethis<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_recursethis&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=lHl6mcA1LFiirClmNasU32yWmIRXU2N8uYMaP0t2ykI&m=7T3yuDhhEfjIbO4hLj0hFJaOPVj6TEk-tYKgP_T0zZE&s=faFf5r4ugrbr6XcW4mnHZtsKOOwME9Cv8xxC-vJhcyc&e=> in b4ada77<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hms-2Ddbmi_docker-2Dimages_commit_b4ada77cd37f285d7d08d1aef26ec2336b847fff&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=lHl6mcA1LFiirClmNasU32yWmIRXU2N8uYMaP0t2ykI&m=7T3yuDhhEfjIbO4hLj0hFJaOPVj6TEk-tYKgP_T0zZE&s=jVeaqJdKrMxCEfjw3wU1VeY1_LNUlfJINOX1HZzSuzM&e=> on Apr 4. Is that really when and by whom it was written?

cc @avillach<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_avillach&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=lHl6mcA1LFiirClmNasU32yWmIRXU2N8uYMaP0t2ykI&m=7T3yuDhhEfjIbO4hLj0hFJaOPVj6TEk-tYKgP_T0zZE&s=O3WFyHmZFthLduu2H-lp8bOeadNGuaNQWnjzcHEqY2g&e=>

**Comment by namdets** [comment]
This jar is a dependency that should have been removed prior to release. We are working on removing it now.

Thanks for pointing it out!

**Comment by recursethis** [comment]
It's been removed. The IRCT codebase will need to be modified. The ojdbc is minimally used (specifically for UMLS lookup) as part of an IRCT extension, not core engine code. UMLS lookup will have to be handled in another way. I'm sure there are available options.

**Comment by dckc** [comment]
Thanks for addressing this right away.

I'd close this, but perhaps you want it open to track "The IRCT codebase will need to be modified."

**Comment by recursethis** [comment]
I've created a ticket in our internal ticketing system to update the IRCT codebase.
